spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sql_join_training
    username: root
    password: adminUser12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
